services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config", "/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "8889:8889"  # Prometheus exporter (optional, for debugging)
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    image: jaegertracing/jaeger:2.5.0
    ports:
      - "16686:16686"  # Jaeger UI

  prometheus:
    image: prom/prometheus:v3.3.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"